version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
  backend:
    build: ./backend
    image: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
