services:
  backend:
    build:
      context: ./backend
    container_name: backend
#    ports:
#      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    network_mode: "host"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
#    ports:
#      - "80:3000"
#    environment:
#      - REACT_APP_API_URL=http://52.67.116.9:5000  # URL para acessar a API Flask
    network_mode: "host"
