services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=localhost  # Use localhost
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mstarsupply_db
    ports:
      - "3306:3306"